name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files and setup environment
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build plugins
      run: composer install --no-dev -o

    - name: Build theme dependencies
      run: npm install && npm run build
      working-directory: wp-content/themes/wally

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: wp-content/
        server-dir: /public_html/wp-content/
        exclude: |
          themes/wally/assets/**
          themes/wally/node_modules/**
          themes/wally/.*
          themes/wally/composer.json
          themes/wally/composer.lock
          themes/wally/package-lock.json
          themes/wally/package.json
          themes/wally/phpcs.xml.dist
          themes/wally/webpack.config.js
          plugins/wally-core/tests/**
          plugins/wally-core/.*
          plugins/wally-core/composer.json
          plugins/wally-core/composer.lock
          plugins/wally-core/package-lock.json
          plugins/wally-core/package.json
          plugins/wally-core/phpcs.xml
          plugins/wally-core/phpunit.xml
